ABBREVIATIONS = {
    # SLURM-related parameters
    # "job_name": "job",
    "nodes": "N",
    "cpus_per_task": "CPUs",
    "memory": "mem",
    "output_file": "out",
    "error_file": "err",
    "nice_value": "nice",
    "partition": "part",
    "qos": "qos",
    "gres": "gres",

    # Conda environment
    "conda_env": "env",

    # Experiment parameters
    "augmentation_type": "aug",
    "dimensionality_reduction": "DR",
    "batch_size": "BS",
    "latent_dims": "LD",
    "num_prototypes": "NP",
    "epsilon": "eps",
    "cvae_loss_scaler": "cvae",
    "prot_decoding_loss_scaler": "PDLS",
    "model_version": "MV",
    "k_neighbors": "kN",
    "experiment_name": "exp",
    'semi_supervised': 'semi',

    # Add any other parameters you need to abbreviate here
    "learning_rate": "LR",
    "optimizer": "opt",
    "dropout_rate": "dropout",
    "activation_function": "act",
    "epochs": "ep",
    "dataset_id": "ds",
    "shuffle": "shuf",
    "validation_split": "val_split",
    "batch_size": 'bs',
    "temperature": "temp",
    'epsilon': "eps",
    'freeze_prototypes_nepochs': 'frz',
    'prot_init': 'prtInit',
    'lambda_proto': 'proto',
    'lambda_commit': 'cmit',
    'loss_type': 'loss',
    'training_type': 'train',
    # 'pretraining_epochs': 'pre-e',
    # 'fine_tuning_epochs': 'tune-e'
    # 'pretraining_epochs': 'pretrain',
    'ft_epochs': 'finetune',
    "cvae_epochs": "cvae_e",
    'decodable_prototypes':  'dec_protos',
    "sinkhorn_iterations": 'sink_itr',
    "hard_clustering": "hard",
    "longest_path": "path",
    "n_components": "ncomp",
    "supervised_ratio": "supervised",
    "multi_layer_protos": "multi-proto",
    "batch_removal_ratio": 'br',
    "use_bknn": 'bknn',
    "freeze_batch_embedding": 'frzbe',
    "freeze_decoder": 'frzdc',
    "batch_sinkhorn": "bsink",
    "weighted_batch": "wb",
    "knn_similarity": 'knnsim',
    "recon_loss": 'recon',
    "no_sinkhorn": 'nosink',
    "mask_probability": 'mask-prob',
    "default_dispertion": 'disp',
    "fold": 'fold',
    "spatial": 'spatial',
    "entropy_reg": "entropy",
    "queue_length": 'qlen',
    "model_type": 'model',
    "l2norm": "l2norm",
    "use_rbf": 'rbf',
    'assignment_metric': 'assn',
    'study_id': 'sid',
    'epoch_queue_starts': 'qe',
    'warmup_epochs': 'warmup',
    'base_lr': 'blr',
    "use_counts": 'raw',
    'knn_method': 'knn',
    'affinity_type': 'aff',
    'covet_alpha': 'ca',
    'cell_w_mode': 'cw',
    'beta': 'beta',
    'lambda_align': 'align',
    'lambda_l2': 'l2n',
    'lambda_recon': 'recon',
    'lambda_kl': 'kl',
    'lambda_balance': 'bal',
    'lambda_swav': 'lswav',
    'lambda_p_uncertainty': 'lp', # l proto uncertainty
    'lambda_proto_entropy': 'lu', # l usage
    'recon_update_target': 'vqrecon',
    'recon_type': 'rt',
    'normalize_loss': 'lnorm',
    'div_type': 'dt',
    'weighted_kl': 'wkl',
    'kl_sched': 'ksc',
    'swav_sched': 'ssc',
    'recon_start_epoch': 'rse',
    'kl_start_epoch': 'kse',
    'opt': 'opt',
    'umap_metric': 'um',
    'full_dataset_mode': 'fdm',
    'adoptive_eps': 'aeps',
    'p': 'p',
    'k_pos': 'kp',
    'softm': 'sm',
    'lambda_aff': 'laff',
    'aff_sim_type': 'afst',
    'two_sided': 'ts',
    'lsim': 'lsim',
    'graph_mode': 'grm',
    'lambda_proto_recon': 'lprec',
    'proto_recon_hard': 'prechrd',
    'lambda_r1r2': 'lr1r2',
    'lambda_umap': 'lumap',
    'umap_similarity': 'usim',
    'umap_proto_metric': 'upm',
    'calibrate_eps': 'ecal',
    'epsilon_start_factor': 'esf',
    'umap_proto_effk_start': 'effks',
    'usage_norm_sim': 'unorm',
    'lambda_degree_weight': 'degw',
    'degree_norm_loss': 'dnl',
    'lambda_proto_usage': 'lpu',
    'proto_usage_mode': 'pum',
    'lambda_nassoc': 'lna',
    'nassoc_alpha': 'naa',
    'nassoc_agg': 'nagg',
    'nassoc_diag_loss': 'nadl',
    'nassoc_diag': 'nad',
    'nassoc_diag_norm': 'nadn',
    'nassoc_gamma': 'nagm',
    'lambda_sim_recon': 'lsr',
    'sim_recon_hidden_dim': 'srhd',
    'sim_recon_target': 'srt',
    'sim_recon_n_eigs': 'srne',
    'sim_recon_diffusion_t': 'srdt',
    'sim_recon_neg_sample': 'srns',
    'jsd_min_dist': 'jsdmd',
    'dist_min_dist': 'dstmd',
    'dist_spread': 'dstsp',
    'proto_decoupled': 'pdec',
    'gmm_eta': 'geta',
    'gmm_eta_end': 'getae',
    'gmm_resurrect': 'gres',
    'gmm_resurrect_thresh': 'grest',
}